spring.datasource.url=jdbc:postgresql://localhost:5432/minipay
spring.application.name=minipay
spring.datasource.username=postgres
spring.datasource.password=Camalion12
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false